# https://github.com/k3d-io/k3d/issues/1108
ARG K3S_TAG="v1.27.4-k3s1"
FROM rancher/k3s:$K3S_TAG as k3s
FROM ubuntu:22.04

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN apt-get update && \
    apt-get -y install gnupg2 curl ca-certificates rpcbind nfs-common nfs-kernel-server containerd curl

RUN RUN curl https://releases.rancher.com/install-docker/24.0.7.sh | sh

COPY --from=k3s /bin /bin
COPY --from=k3s /etc /etc

RUN mkdir -p /etc && \
    echo 'hosts: files dns' > /etc/nsswitch.conf

RUN chmod 1777 /tmp

VOLUME /var/lib/kubelet
VOLUME /var/lib/rancher/k3s
VOLUME /var/lib/cni
VOLUME /var/log

ENV PATH="$PATH:/bin/aux"

ENTRYPOINT ["/bin/k3s"]
CMD ["agent"]